---
title: "PrelimTables"
output: pdf_document
date: "2024-11-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(igraph)
library(network)
library(intergraph)
library(ergm)
library(gridExtra)
library(RColorBrewer)
library(ggpubr)
library(kableExtra)
```

## Reading and plotting results data - MCAR Cohesive

```{r}
#getwd()
param <- "InitParamMiss_Cohesive_MCAR.rds"
#param_c <- "InitParamMiss_Cohesive_MCAR.rds"
fileStrt <- "CoDaOP/MCAR/InitParamMiss_Cohesive_MCAR_OP"
Ncombo <- c(1:144)#c(1,2, 4:46, 48:72, 74:144)
#my.plots <- vector(length(Ncombo), mode='list')

S <- as.data.frame(readRDS(param))

## Might have to change the below based on the simulation param combo
S$pC <- rep(rep(c("High", "Med", "Low"), each = 6), times = 8)
S$pClust <- rep(rep(c("equal","unequal"), each = 18),times = 4)
S$pClustOL <- rep(c("NoOL","2OL","3OL","allOL"), each = 36)
S$missing <- rep(c(0,5,10,15,25,35), times = 24)
## Creating empty dataframes for saving output
## Full data dataframes
## Number of columns depends on the number of clusters and covariates.
## The 4 is to save all the log likelihoods separately.
FinCov <- as.data.frame(matrix(nrow= 0 , ncol = 1+1+4+1+1+(S[1,]$k_out*2)+ 1,0))
## Dataframes for no covariates runs
FinnoCov <- as.data.frame(matrix(nrow= 0 , ncol = 1+1+4+1+1+1, 0))
## NWdir total
## Setting up plot rds
plotRDS <- list()
ploti <- 1
NWDirT <- as.data.frame(matrix(nrow = 0, ncol = 9, 0))
pdf("SplitSumaryPlotsMCAR.pdf")
for(i in Ncombo){
  FdatCov <- as.data.frame(matrix(nrow = 0 , 
                                  ncol = 1+1+4+1+1+(S[i,]$k_out*2)+1,
                                  0))
  FdatnoCov <- as.data.frame(matrix(nrow = 0 , 
                                    ncol = 1+1+4+1+1+1, 
                                    0))
  
  op <- readRDS(paste0(fileStrt, i,".rds"))
  NWDir <- expand_grid(1:S[i,]$bigN,
                       c("dir", "undir"),
                       1:S[i,]$Nsim,
                       S[i,]$pC,
                       S[i,]$pClust,
                       S[i,]$pClustOL,
                       S[i,]$missing)
  colnames(NWDir) <- c("BigN","DirType","Nsim","pC","pClust","OL","Missing")
  NWDir$j <- 1:dim(NWDir)[1]
  NWDir$i <- i
  ## save the Log likelihood, Omega Index, ARI, Acc or MSE 
  covType <- as.character(S[i,]$covType)
  
  
  for(j in 1:dim(NWDir)[1]){
    ## Saving simulation with covariates
    if(covType == "binary"){
      datCov <- cbind(i,j,op[[1]][[j]]$Loglik, 
                      op[[1]][[j]]$OmegaIndex, 
                      op[[1]][[j]]$ARI, 
                      op[[1]][[j]]$Acc,
                      c(1:dim(op[[1]][[j]]$Loglik)[1]))
      
      if(nrow(op[[1]][[j]]$AccMD) > 0 ){
        datCov <- cbind(datCov, op[[1]][[j]]$AccMD)
      }else{
        datCov <- cbind(datCov, 0,0,0)
      }
      
      ## Saving the final value of the simulation
      FinCov <- rbind(FinCov, datCov[dim(datCov)[1],])
    }
    ## Saving simulations without covariates
    datnoCov <- cbind(i,j, op[[2]][[j]]$Loglik, 
                      op[[2]][[j]]$OmegaIndex, 
                      op[[2]][[j]]$ARI,
                      1:dim(op[[2]][[j]]$Loglik)[1])
    
    ## Saving the final value of the simulation
    FinnoCov <- rbind(FinnoCov, datnoCov[dim(datnoCov)[1],])
    
    FdatCov <- rbind(FdatCov , datCov)
    FdatnoCov <- rbind(FdatnoCov, datnoCov)
  }
  # ## Adding to NW list
  NWDirT <- rbind(NWDirT, NWDir)
  ## Setting column names for all the above
  ## Simulation with covariates
  colnames(FdatCov) <- c("i","j","LLFull", "LLG","LLX","LLZ","OI","ARI",
                         paste0("Acc",1:S[i,]$k_out ), "seq",
                         paste0("AccMD",1:S[i,]$k_out ))
  FdatCov <- left_join(FdatCov, NWDir, by = c("j" = "j", "i" = "i"))
  
  #Simulation w/o covariates
  colnames(FdatnoCov) <- c("i" ,"j","LLFull", "LLG","LLX","LLZ","OI","ARI","seq")
  FdatnoCov <- left_join(FdatnoCov, NWDir, by = c("j" = "j", "i" = "i"))
  
  ## Setting up the prelims plots Covariate data
  p <- list()
  r <- list()
  
  FdatCov$bigNDir <- paste0(FdatCov$BigN, "_",FdatCov$DirType)
  q <- list()
  q[[1]] <- FdatCov %>%
    ggplot()+
    geom_line(aes(x = seq,
                  y = round(LLFull,1),
                  color = as.factor(BigN),
                  group = as.factor(j)),
              show.legend = FALSE) +
    ylab("total Loglikelihood") + xlab("Iteration") +
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~bigNDir, nrow =3) + theme(axis.ticks.length=unit(.25, "cm"))+
    theme_minimal()
  
  q[[2]] <- FdatCov %>%
    ggplot()+
    geom_line(aes(x = seq,
                  y = round(OI,1),
                  color = as.factor(BigN),
                  group = as.factor(j)),
              show.legend = FALSE) +
    ylab("Omega Index") + xlab("Iteration") +
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~bigNDir, nrow=3) +theme(axis.ticks.length=unit(.25, "cm"))+
    theme_minimal()
  
  #qt <- ggpubr::ggarrange(plotlist = q[[1]], nrow = 3)
  qtTot1 <- ggpubr::annotate_figure(q[[1]],
                                    top = ggpubr::text_grob(paste0("Overlap: ", S[i,]$pClustOL,
                                                                   " Cov Corr: ", S[i,]$pC,
                                                                   " Pct Missing: ",S[i,]$missing,
                                                                   " Clust size: ",S[i,]$pClust),
                                                            color = "darkblue",
                                                            face = "bold",
                                                            size = 14))
  print(qtTot1)
  qtTot2 <- ggpubr::annotate_figure(q[[2]],
                                    top = ggpubr::text_grob(paste0("Overlap: ", S[i,]$pClustOL,
                                                                   " Cov Corr: ", S[i,]$pC,
                                                                   " Pct Missing: ",S[i,]$missing,
                                                                   " Clust size: ",S[i,]$pClust),
                                                            color = "darkblue",
                                                            face = "bold",
                                                            size = 14))
  print(qtTot2)  
  
  
  
  p[[1]] <- FdatCov %>%
    ggplot() +
    geom_line(aes(x = seq,
                  y = round(LLFull,1),
                  color = as.factor(BigN),
                  group = as.factor(j)),
              show.legend = FALSE) +
    #geom_vline(aes(xintercept = GTll[j,1])) +
    ylab("total Loglikelihood") + xlab("Iteration")+
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~DirType)+
    theme_minimal()
  
  r[[1]] <- FdatCov %>%
    ggplot() +
    geom_line(aes(x = seq,
                  y = round(LLFull,1),
                  color = as.factor(BigN),
                  group = as.factor(j)),
              show.legend = FALSE) +
    #geom_vline(aes(xintercept = GTll[j,1])) +
    ylab("total Loglikelihood") + xlab("Iteration")+
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~DirType)+
    theme_minimal()
  
  r[[2]] <- FdatCov %>%
    ggplot() +
    geom_line(aes(x = seq,
                  y = round(LLG,1),
                  color = as.factor(BigN),
                  group = as.factor(j)),
              show.legend = FALSE) +
    #geom_vline(aes(xintercept = GTll[j,1])) +
    ylab("Graph Loglikelihood") + xlab("Iteration")+
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~DirType)+
    theme_minimal()
  
  r[[3]] <- FdatCov %>%
    ggplot() +
    geom_line(aes(x = seq,
                  y = round(LLX,1),
                  color = as.factor(BigN),
                  group = as.factor(j)),
              show.legend = FALSE) +
    #geom_vline(aes(xintercept = GTll[j,1])) +
    ylab("Binary Loglikelihood") + xlab("Iteration")+
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~DirType)+
    theme_minimal()
  
  p[[2]] <- FdatCov %>%
    ggplot() +
    geom_point(aes(x = seq,
                   y = round(OI,3),
                   color = as.factor(BigN),
                   group = as.factor(j)),
               size  = 0.1,
               show.legend = FALSE) + ylab("Omega Idx")+xlab("Iteration")+
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~DirType)+
    theme_minimal()
  
  if(S[j,]$k_in+S[j,]$k_out > 0){
    FdatCov$AccAvg <- (FdatCov$Acc1 +FdatCov$Acc2 + FdatCov$Acc3)/3
    FdatCov$AccMDAvg <- (FdatCov$AccMD1 +FdatCov$AccMD2 + FdatCov$AccMD3)/3
    
    p[[3]] <- FdatCov %>%
      ggplot() +
      geom_line(aes(x = seq,
                    y = AccAvg,
                    color = as.factor(BigN),
                    group = as.factor(j)),
                size  = 0.1,
                show.legend = FALSE) +
      #scale_x_continuous(guide = guide_axis(angle = 45), limits = c(0.75, NA)) +
      #scale_y_continuous(limits = c(0.3, 1), expand = c(0,0))+
      xlab("Avg Accuracy for Cov") + ylab("Iteration") +
      facet_wrap(~DirType) +
      theme_minimal()
    
    p[[4]] <-  FdatCov %>%
      ggplot() +
      geom_line(aes(x = seq,
                    y= AccMDAvg,
                    group = as.factor(j),
                    color = as.factor(BigN)),
                size  = 0.1,
                show.legend = FALSE) +
      xlab("Avg Accuracy for out Cov Missing Data") + ylab("Iteration") + facet_wrap(~DirType)+
      theme_minimal()
  }
  pt <- ggpubr::ggarrange(plotlist = p, ncol = 2, nrow = 2)
  
  ptTot <- ggpubr::annotate_figure(pt,
                                   top = ggpubr::text_grob(paste0("Overlap: ", S[i,]$pClustOL,
                                                                  " Cov Corr: ", S[i,]$pC,
                                                                  " Pct Missing: ",S[i,]$missing,
                                                                  " Clust size: ",S[i,]$pClust),
                                                           color = "darkblue",
                                                           face = "bold",
                                                           size = 14))
  print(ptTot)
  
  rt <- ggpubr::ggarrange(plotlist = r, ncol = 2, nrow = 2)
  rtTot <- ggpubr::annotate_figure(rt,
                                   top = ggpubr::text_grob("Log Likelihood split",
                                                           color = "darkblue",
                                                           face = "bold",
                                                           size = 14))
  print(rtTot)
  # Setting up the prelims plots
  pn <- list()
  pn[[1]] <- FdatnoCov %>%
    ggplot() +
    geom_line(aes(x = seq,
                  y = round(LLFull,1),
                  color = as.factor(BigN),
                  group = as.factor(j)),
              show.legend = FALSE) +
    #geom_vline(aes(xintercept = GTll[j,1])) +
    ylab("total Loglikelihood") + xlab("Iteration")+
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~DirType)+
    theme_minimal()
  
  
  pn[[2]] <- FdatnoCov %>%
    ggplot() +
    geom_point(aes(x = seq,
                   y = round(OI,3),
                   color = as.factor(BigN),
                   group = as.factor(j)),
               size  = 0.1,
               show.legend = FALSE) +
    ylab("Omega Idx")+xlab("Iteration")+
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~DirType)+
    theme_minimal()
  
  ptn <- ggpubr::ggarrange(plotlist = pn, ncol = 2, nrow = 2)
  ptnTot <- ggpubr::annotate_figure(ptn,
                                    top = ggpubr::text_grob(paste0("Overlap: ", S[i,]$pClustOL,
                                                                   " Cov Corr: ", S[i,]$pC,
                                                                   " Pct Missing: ",S[i,]$missing,
                                                                   " Clust size: ",S[i,]$pClust),
                                                            color = "darkblue",
                                                            face = "bold",
                                                            size = 14))
  print(ptnTot)
  plotRDS <- append(plotRDS, list(list(ptTot, rtTot, ptnTot, qtTot1, qtTot2)))
}
saveRDS(plotRDS, file = "MCARplots.rds")
dev.off()
```

```{r}

rdsDat <- readRDS("MCARplots.rds")
q <- list()
r <- list()
#pdf("CommDet3rdanalysisPlots.pdf")
for(i in c(44,52,74,125)){
  #q[[i]] <- rdsDat[[i]][[4]]
  #  r[[i]] <- rdsDat[[i]][[5]]
  #  if(i %in% c(44,52,74,125)){
  print(rdsDat[[i]][[1]])
  print(rdsDat[[i]][[2]])
  print(rdsDat[[i]][[5]])
  # print(rdsDat[[i]][[3]])
  #  }
}
#dev.off()
## 44, 125, 74, 52, 46
```

```{r}
colnames(FinCov) <- c("i","j","LLFull", "LLG","LLX","LLZ","OI","ARI",
                      paste0("Acc",1:S[i,]$k_out ), "seq",
                      paste0("AccMD",1:S[i,]$k_out ))
#Simulation w/o covariates
colnames(FinnoCov) <- c("i","j","LLFull", "LLG","LLX","LLZ","OI","ARI","seq")

colnames(NWDirT) <- colnames(NWDir)

## Joining the data frame with types for NW list
## NW with covariates
FinCov <- left_join(FinCov , NWDirT, by = c("j" = "j", "i" = "i"))

## NW without covariates
FinnoCov <- left_join(FinnoCov , NWDirT, by = c("j" = "j", "i" = "i"))
FdatnoCov <- left_join(FdatnoCov, NWDirT, by = c("j" = "j", "i" = "i"))
FinCov$AccAvg <- (FinCov$Acc1 + FinCov$Acc2 + FinCov$Acc3)/3
FinCov$AccMDAvg <- (FinCov$AccMD1 + FinCov$AccMD2 + FinCov$AccMD3)/3
FinCov$OL <- factor(FinCov$OL,levels = c("NoOL", "2OL", "3OL", "allOL"))
FinCov$pC <- factor(FinCov$pC, levels = c("High", "Med","Low"))

FinnoCov$OL <- factor(FinnoCov$OL,levels = c("NoOL", "2OL", "3OL", "allOL"))
FinnoCov$pC <- factor(FinnoCov$pC, levels = c("High", "Med","Low"))

## Omega Index
pdf("SummaryBoxplotsMCAR_B15.pdf")
print(FinCov[FinCov$pClust == "equal", ] %>%
        ggplot()+
        geom_boxplot(aes(y = OI, x = as.factor(Missing), 
                         color = as.factor(DirType)))+
        ggtitle("Equal Sized clusters w/ Covariates")+ xlab("Percentage missing")+
        ylab("Omega Index")+labs(color ="NW direction")+lims(y = c(0.4, 1.1))+
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol =3))

print(FinCov[FinCov$pClust == "unequal", ] %>%
        ggplot()+
        geom_boxplot(aes(y = OI, x = as.factor(Missing), 
                         color = as.factor(DirType)))+
        ggtitle("Unequal clusters w/ Covariates")+ xlab("Percentage missing")+
        ylab("Omega Index")+labs(color ="NW direction")+lims(y = c(0.4, 1.1))+
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol =3))

## Full accuracy
print(FinCov[FinCov$pClust == "equal", ] %>%
        ggplot() +
        geom_boxplot(aes(y = AccAvg, x = as.factor(Missing), 
                         color = as.factor(DirType))) +
        ggtitle("Equal Sized clusters Accuracy")+ xlab("Percentage missing") +
        ylab("Prediction Accuracy") + labs(color ="NW direction") +
        theme(legend.position ='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol = 3))

print(FinCov[FinCov$pClust == "unequal", ] %>%
        ggplot() +
        geom_boxplot(aes(y = AccAvg, x = as.factor(Missing), 
                         color = as.factor(DirType))) +
        ggtitle("Unequal clusters Accuracy")+ xlab("Percentage missing") +
        ylab("Prediction Accuracy") + labs(color ="NW direction") +
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol = 3))

## Missing data accuracy
print(FinCov[FinCov$pClust == "equal", ] %>%
        ggplot() +
        geom_boxplot(aes(y = AccMDAvg, x = as.factor(Missing), 
                         color = as.factor(DirType))) +
        ggtitle("Equal Sized clusters Accuracy Missing data only")+ xlab("Percentage missing") +
        ylab("Prediction Accuracy Missing Data") + labs(color ="NW direction") +
        theme(legend.position ='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol = 3))

print(FinCov[FinCov$pClust == "unequal", ] %>%
        ggplot() +
        geom_boxplot(aes(y = AccMDAvg, x = as.factor(Missing), 
                         color = as.factor(DirType))) +
        ggtitle("Unequal clusters Accuracy Missing data only")+ xlab("Percentage missing") +
        ylab("Prediction Accuracy Missing Data") + labs(color ="NW direction") +
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol = 3))

### No covariates
print(FinnoCov[FinCov$pClust == "equal", ] %>%
        ggplot()+
        geom_boxplot(aes(y = OI, x = as.factor(Missing), 
                         color = as.factor(DirType)))+
        ggtitle("Equal Sized clusters w/o covariates")+ xlab("Percentage missing")+
        ylab("Omega Index")+labs(color ="NW direction")+lims(y = c(0.4, 1.1))+
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol =3))

print(FinnoCov[FinCov$pClust == "unequal", ] %>%
        ggplot()+
        geom_boxplot(aes(y = OI, x = as.factor(Missing), 
                         color = as.factor(DirType)))+
        ggtitle("Unequal clusters w/o covariates")+ xlab("Percentage missing")+
        ylab("Omega Index")+labs(color ="NW direction")+ lims(y = c(0.4, 1.1))+
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol =3))
dev.off()

saveRDS(plotRDS, "SummaryPlotsMCAR_B15.rds")
saveRDS(list(FinCov, FinnoCov),"FinalMCAR_B15.rds")

```

Generating a table with summarized data

```{r}
df <- readRDS("FinalMCAR_B15.rds")
FinCov <- df[[1]]
FinnoCov <- df[[2]]

df_FinCov <- FinCov %>%
  dplyr::group_by(i,BigN,DirType, pC,pClust,OL,Missing) %>%
  summarise(meanOI = mean(OI),
            meanAccAvg = mean(AccAvg),
            meanAccMDAvg = mean(AccMDAvg))
print(df_FinCov[df_FinCov$pClust == "unequal", ] %>%
        ggplot()+
        geom_boxplot(aes(y = meanAccAvg, x = as.factor(Missing), 
                         color = as.factor(DirType)))+
        ggtitle("Unequal clusters")+ xlab("Percentage missing")+
        ylab("Average accuracy")+labs(color ="NW direction")+ lims(y = c(0.4, 1.1))+ scale_color_manual(values = c("blue2","deepskyblue2"))+
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol =3))

print(df_FinCov[df_FinCov$pClust == "equal", ] %>%
        ggplot()+
        geom_boxplot(aes(y = meanAccAvg, x = as.factor(Missing), 
                         color = as.factor(DirType)))+
        ggtitle("Equal clusters")+ xlab("Percentage missing")+
        ylab("Average accuracy")+labs(color ="NW direction")+ lims(y = c(0.4, 1.1))+ scale_color_manual(values = c("blue2","deepskyblue2"))+
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol =3))

print(df_FinCov[df_FinCov$pClust == "unequal", ] %>%
        ggplot()+
        geom_boxplot(aes(y = meanAccMDAvg, x = as.factor(Missing), 
                         color = as.factor(DirType)))+
        ggtitle("Unequal clusters")+ xlab("Percentage missing")+ scale_color_manual(values = c("blue2","deepskyblue2"))+
        ylab("Average accuracy Missing Data Only")+labs(color ="NW direction")+ lims(y = c(0.4, 1.1))+
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol =3))

print(df_FinCov[df_FinCov$pClust == "equal", ] %>%
        ggplot()+
        geom_boxplot(aes(y = meanAccMDAvg, x = as.factor(Missing), 
                         color = as.factor(DirType)))+
        ggtitle("Equal clusters")+ xlab("Percentage missing")+scale_color_manual(values = c("blue2","deepskyblue2"))+
        ylab("Average accuracy Missing Data Only")+labs(color ="NW direction")+ lims(y = c(0.4, 1.1))+
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol =3))


df_FinnoCov <- FinnoCov %>%
  dplyr::group_by(i,BigN,DirType, pC,pClust,OL,Missing) %>%
  summarise(meanOI = mean(OI))


df_FinCov$Cov <- "Cov"
df_FinnoCov$Cov <- "NoCov"

df_Fin <- rbind(df_FinCov,df_FinnoCov)

print(df_Fin[df_Fin$pClust == "equal", ] %>%
        ggplot()+
        geom_boxplot(aes(y = meanOI, x = as.factor(Missing), 
                         color = interaction(as.factor(DirType),Cov)))+
        ggtitle("Equal clusters")+ xlab("Percentage missing")+
        ylab("Omega Index")+
        labs(color ="NW direction & covariate inclusion")+ lims(y = c(0.4, 1.1))+ 
        scale_color_manual(values = c("blue2","deepskyblue2","brown2","darkred"))+
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol =3))

print(df_Fin[df_Fin$pClust == "unequal", ] %>%
        ggplot()+
        geom_boxplot(aes(y = meanOI, x = as.factor(Missing), 
                         color = interaction(as.factor(DirType),Cov)))+
        ggtitle("Unequal clusters")+ xlab("Percentage missing")+
        ylab("Omega Index")+
        labs(color ="NW direction & covariate inclusion")+ lims(y = c(0.4, 1.1)) + 
        scale_color_manual(values = c("blue2","deepskyblue2","brown2","darkred")) +
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol =3))

#png("EqclustNoOL_HighOL.png")
pdf("EqclustNoOL_HighOL.pdf")
print(
  df_Fin %>%
    filter(pClust == "equal"& Cov == "Cov" & (OL == "NoOL" | OL == "allOL") ) %>%
    mutate(OverLap_Corr = paste0(OL,"-",pC)) %>%
    ggplot()+
    geom_boxplot(aes(y = meanOI, x = as.factor(Missing), 
                     color = as.factor(DirType)))+
    ggtitle("Omega index for equal sized clusters at various percent missing values")+ xlab("Percentage missing")+ labs(subtitle = "Compared on level of overlap and covariates to community correlation")+
    ylab("Omega Index")+
    labs(color ="Network direction")+ lims(y = c(0.4, 1.1))+ 
    scale_color_manual(labels = c("Directed", "Undirected"), values = c("blue2","deepskyblue2","brown2","darkred"))+
    theme_minimal()+
    theme(legend.position='bottom', 
          strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
    facet_wrap(~factor(OverLap_Corr, 
                       levels = c("NoOL-High","NoOL-Med","NoOL-Low",
                                  "allOL-High","allOL-Med","allOL-Low")), 
               ncol =3))
dev.off()

#png("EqclustCov_Nocov_Dir.png")
pdf("EqclustCov_Nocov_Dir.pdf")
print(
  df_Fin %>%
    filter(pClust == "equal" & DirType== "dir" & (OL == "NoOL" | OL == "allOL") ) %>%
    mutate(OverLap_Corr = paste0(OL,"-",pC)) %>%
    ggplot()+
    geom_boxplot(aes(y = meanOI, x = as.factor(Missing), 
                     color = as.factor(Cov)))+
    ggtitle("Omega index for equal sized clusters at various percent missing values") + 
    xlab("Percentage missing") + 
    labs(subtitle = "Compared on level of overlap and covariate inclusion in networks") +
    ylab("Omega Index") +
    labs(color ="Covariate inclusion") + 
    lims(y = c(0.4, 1.1)) + 
    scale_color_manual(labels = c("Covariate", "No Covariate"), values = c("brown2","darkred"))+
    theme_minimal()+
    theme(legend.position='bottom', 
          strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
    facet_wrap(~factor(OverLap_Corr, 
                       levels = c("NoOL-High","NoOL-Med","NoOL-Low",
                                  "allOL-High","allOL-Med","allOL-Low")), 
               ncol =3))
dev.off()

#png("Accuracy_dir_undir.png")
pdf("Accuracy_dir_undir.pdf")
df_Fin %>%
  filter(Cov == "Cov" & pClust == "equal" & (OL == "NoOL" | OL == "allOL")) %>%
  group_by(i,DirType, pC,OL,Missing) %>%
  summarise(meanAcc  = mean(meanAccAvg), sdAcc = sd(meanAccAvg)) %>%
  ungroup()%>%
  ggplot()+
  geom_line(aes(x = Missing, y = meanAcc, linetype = DirType, color = OL))+
  geom_point(aes(x = Missing, y = meanAcc, color = OL))+
  scale_x_continuous(breaks = c(unique(df_Fin$Missing)))+
  scale_color_manual(labels = c("No overlap", "High overlap"), values = c("chartreuse3","darkgreen"))+
  scale_linetype_manual(values = c("dir" =1, "undir"=2), labels = c("Directed", "undirected"))+
  labs(title="Overall accuracy at multiple levels of correlation between community and covariates",subtitle = "Non overlapping networks vs overlapping networks at various percent missing values" ,x = "Percentage of missing covariates", y = "Accuracy of prediction",
       linetype ="Network direction", color = "Overlap level")+
  theme_minimal()+
  theme(legend.position='bottom', 
        strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm")),
        plot.title = element_text(hjust = 1)) +
  facet_wrap(~pC, ncol=3 )
dev.off()
#png("AccuracyMD_dir_undir.png")
pdf("AccuracyMD_dir_undir.pdf")

df_Fin %>%
  filter(Cov == "Cov" & pClust == "equal" & (OL == "NoOL" | OL == "allOL") & !(Missing == 0)) %>%
  group_by(i,DirType, pC,OL,Missing) %>%
  summarise(meanAccMD  = mean(meanAccMDAvg), sdAcc = sd(meanAccMDAvg)) %>%
  ungroup()%>%
  ggplot()+
  geom_line(aes(x = Missing, y = meanAccMD, linetype = DirType, color = OL))+
  geom_point(aes(x = Missing, y = meanAccMD, color = OL))+
  scale_x_continuous(breaks = c(unique(df_Fin$Missing)))+
  scale_color_manual(labels = c("No overlap", "High overlap"), values = c("chartreuse3","darkgreen"))+
  scale_linetype_manual(values = c("dir" =1, "undir"=2), labels = c("Directed", "undirected"))+
  labs(title="Accuracy at multiple levels of correlation between community and covariates",
       subtitle = "Non overlapping networks vs overlapping networks at various percent missing values",
       x = "Percentage of missing covariates", 
       y = "Accuracy of prediction",
       linetype ="Network direction", 
       color = "Overlap level")+
  theme_minimal()+
  theme(legend.position='bottom', 
        strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
  facet_wrap(~pC, ncol=3 )
dev.off()

## comparing the omega index values for no missing data to show inclusion of covariates helps
#png("Dir_cov_undir_nocov.png")
pdf("Dir_cov_undir_nocov.pdf")
print(df_Fin %>%
        filter(Missing == 0) %>%
        mutate(Cov_Dir = paste0(Cov,"-",DirType)) %>%
        filter(Cov_Dir == "Cov-dir" | Cov_Dir == "NoCov-undir") %>%
        ggplot()+
        geom_boxplot(aes(x = pC, y = meanOI, color = Cov_Dir)) +
        scale_color_manual(labels = c("Covariate+Directed", "No Covariate + Undirected"), 
                           values = c("blue2","brown2","deepskyblue2","darkred"))+
        labs(title="Omega Index at multiple levels of correlation between community and covariates",
             subtitle = "Various community overlap levels and cluster size distribution",
             x = "Community Covariate Overlap", 
             y = "Omega Index")+
        theme_minimal()+
        theme(legend.position='bottom', legend.title=element_blank(),
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm")))+
        facet_wrap(~pClust+OL, ncol = 4))
dev.off()

```

## Reading and plotting results data MCAR Cohesive Continuous var.

```{r}
opf_Regcov <- lst4[[1]]
j <- 2
## Plotting the residual error value against response
Yres <- opf_Regcov[[j]]$Zout_cov
Yorig <- as.data.frame(vertex_attr(Gtot[[1]]))[,c(4:6)]
X <- cbind(1, opf_Regcov[[j]]$Ffin, opf_Regcov[[j]]$Hfin)
beta <- opf_Regcov[[j]]$betaout
df <-data.frame(matrix(nrow = 0, ncol = 6,0 ))
for(i in 1:3){
  pred <-  beta[i,] %*% t(X)
  residR <- Yres[,i] - pred
  residO <- Yorig[,i] - (pred )#* (max(Yorig[,i], na.rm = TRUE) - min(Yorig[,i], na.rm = TRUE)) + min(Yorig[,i], na.rm = TRUE))
  
  df <- rbind(df, cbind(i, 
                        c(pred), 
                        c(residR), 
                        c(residO),
                        c(Yres[,i]), #* (max(Yorig[,i], na.rm = TRUE) - min(Yorig[,i], na.rm = TRUE)) + min(Yorig[,i], na.rm = TRUE)), 
                        Yorig[,i]))
}

colnames(df) <- c("i", "Pred", "residR","residO","Yr","Yo")

## plotting the residual vs predictors

ggplot(df) + geom_point(aes(y = residR, x = Yr))+facet_wrap(~i, scales = "free")

## Residuals vs fitted plot
ggplot(df) + geom_point(aes(y = residR, x = Pred))+facet_wrap(~i, scales = "free")


## Plotting log lik values
logl <- data.frame(opf_Regcov[[j]]$Loglik)

colnames(logl) <- c("Tot", "Grph","Bin","Cont")
logl$seq <- 1:dim(logl)[1]
logl <- logl %>% 
  pivot_longer(-c(seq))

ggplot(logl)+
  geom_line(aes(x = seq, y = value, color = name))
#facet_wrap(~name, scales = "free")

df_op <- data.frame(cbind(OI = opf_Regcov[[j]]$OmegaIndex,
                          MSE1 = opf_Regcov[[j]]$MSE[,1],
                          MSE2 = opf_Regcov[[j]]$MSE[,2],
                          MSE3 = opf_Regcov[[j]]$MSE[,3],
                          seq = 1:dim(opf_Regcov[[j]]$MSE)[1]))

df_op %>% ggplot()+geom_point(aes(x = seq, y = OI))
df_op %>% ggplot()+geom_point(aes(x = seq, y = MSE1))
df_op %>% ggplot()+geom_point(aes(x = seq, y = MSE2))
df_op %>% ggplot()+geom_point(aes(x = seq, y = MSE3))



```

## Reading and plotting results data - MAR Cohesive

Data is missing depending on the covariates
```{r}

param <- "InitParamMiss_Cohesive_MAR.rds"
param_c <- "InitParamMiss_Cohesive_MAR.rds"
fileName <- list.files("CoDAOP/MAR/")
#Ncombo <- c(1:144)#c(1,2, 4:46, 48:72, 74:144)
S <- as.data.frame(readRDS(param))

## Might have to change the below based on the simulation param combo
S$pC <- rep(rep(c("High", "Med", "Low"), each = 4), times = 8)
S$pClust <- rep(rep(c("equal","unequal"), each = 12),times = 4)
S$pClustOL <- rep(c("NoOL","2OL","3OL","allOL"), each = 24)
S$missing <- rep(c("s5","s10","d5","s25s5"), times = 24)
S$simN <- 1:dim(S)[1]
## Creating empty dataframes for saving output
## Full data dataframes
## Number of columns depends on the number of clusters and covariates.
## The 4 is to save all the log likelihoods separately.
FinCov <- as.data.frame(matrix(nrow= 0 , ncol = 1+1+4+1+1+(S[1,]$k_out*2)+ 1,0))

## Dataframes for no covariates runs
FinnoCov <- as.data.frame(matrix(nrow= 0 , ncol = 1+1+4+1+1+1, 0))
## NWdir total
## Setting up plot rds
ploti <- 1
NWDirT <- as.data.frame(matrix(nrow = 0, ncol = 9, 0))
i <- 1
pdf("SummaryPlotsMAR.pdf")
for (file in fileName) {
  
  FdatCov <- as.data.frame(matrix(nrow = 0 , 
                                  ncol = 1+1+4+1+1+(S[i,]$k_out*2)+1,
                                  0))
  FdatnoCov <- as.data.frame(matrix(nrow = 0 , 
                                    ncol = 1+1+4+1+1+1, 
                                    0))
  
  op <- readRDS(paste0("CoDAOP/MAR/",file))
  NWDir <- expand_grid(1:S[i,]$bigN,c("dir", "undir"), 1:S[i,]$Nsim, S[i,]$pC, 
                       S[i,]$pClust, S[i,]$pClustOL, S[i,]$missing)
  colnames(NWDir) <- c("BigN","DirType","Nsim","pC","pClust","OL","Missing")
  NWDir$j <- 1:dim(NWDir)[1]
  NWDir$i <- i
  covType <- as.character(S[i,]$covType)
  
  for( j in 1:dim(NWDir)[1] ){
    
    ## Saving simulation with covariates
    if(covType == "binary"){
      datCov <- cbind(i, j, op[[1]][[j]]$Loglik, op[[1]][[j]]$OmegaIndex, op[[1]][[j]]$ARI, 
                      op[[1]][[j]]$Acc, c(1:dim(op[[1]][[j]]$Loglik)[1]))
      
      if(nrow(op[[1]][[j]]$AccMD) > 0 ){
        datCov <- cbind(datCov, op[[1]][[j]]$AccMD)
      }else{
        datCov <- cbind(datCov, 0,0,0)
      }
      
      ## Saving the final value of the simulation
      FinCov <- rbind(FinCov, datCov[dim(datCov)[1],])
    }
    
    ## Saving simulations without covariates
    datnoCov <- cbind(i,j, op[[2]][[j]]$Loglik, 
                      op[[2]][[j]]$OmegaIndex, 
                      op[[2]][[j]]$ARI,
                      1:dim(op[[2]][[j]]$Loglik)[1])
    
    ## Saving the final value of the simulation
    FinnoCov <- rbind(FinnoCov, datnoCov[dim(datnoCov)[1],])
    
    FdatCov <- rbind(FdatCov , datCov)
    FdatnoCov <- rbind(FdatnoCov, datnoCov)
    
  }
  ## Adding to NW list
  NWDirT <- rbind(NWDirT, NWDir)
  ## Setting column names for all the above 
  ## Simulation with covariates
  colnames(FdatCov) <- c("i","j","LLFull", "LLG","LLX","LLZ","OI","ARI",
                         paste0("Acc",1:S[i,]$k_out ), "seq",
                         paste0("AccMD",1:S[i,]$k_out ))
  FdatCov <- left_join(FdatCov, NWDir, by = c("j" = "j", "i" = "i"))
  
  #Simulation w/o covariates
  colnames(FdatnoCov) <- c("i" ,"j","LLFull", "LLG","LLX","LLZ","OI","ARI","seq")
  FdatnoCov <- left_join(FdatnoCov, NWDir, by = c("j" = "j", "i" = "i"))
  
  ## Setting up the prelims plots Covariate data
  p <- list()
  r <- list()
  p[[1]] <- FdatCov %>%
    ggplot() +
    geom_line(aes(y = seq, 
                  x = round(LLFull,1), 
                  color = as.factor(BigN),
                  group = as.factor(j)),
              show.legend = FALSE) +
    #geom_vline(aes(xintercept = GTll[j,1])) +
    xlab("total Loglikelihood") + ylab("Iteration")+
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~DirType)+
    theme_minimal()
  
  r[[1]] <- FdatCov %>%
    ggplot() +
    geom_line(aes(y = seq, 
                  x = round(LLFull,1), 
                  color = as.factor(BigN),
                  group = as.factor(j)),
              show.legend = FALSE) +
    #geom_vline(aes(xintercept = GTll[j,1])) +
    xlab("total Loglikelihood") + ylab("Iteration")+
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~DirType)+
    theme_minimal()
  
  r[[2]] <- FdatCov %>%
    ggplot() +
    geom_line(aes(y = seq, 
                  x = round(LLG,1), 
                  color = as.factor(BigN),
                  group = as.factor(j)),
              show.legend = FALSE) +
    #geom_vline(aes(xintercept = GTll[j,1])) +
    xlab("Graph Loglikelihood") + ylab("Iteration")+
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~DirType)+
    theme_minimal()
  
  r[[3]] <- FdatCov %>%
    ggplot() +
    geom_line(aes(y = seq, 
                  x = round(LLX,1), 
                  color = as.factor(BigN),
                  group = as.factor(j)),
              show.legend = FALSE) +
    #geom_vline(aes(xintercept = GTll[j,1])) +
    xlab("Binary Loglikelihood") + ylab("Iteration")+
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~DirType)+
    theme_minimal()
  
  p[[2]] <- FdatCov %>%
    ggplot() +
    geom_point(aes(y = seq, 
                   x = round(OI,3), 
                   color = as.factor(BigN), 
                   group = as.factor(j)), 
               size  = 0.1,
               show.legend = FALSE) + xlab("Omega Idx")+ylab("Iteration")+
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~DirType)+
    theme_minimal()
  
  if(S[j,]$k_in+S[j,]$k_out > 0){
    FdatCov$AccAvg <- (FdatCov$Acc1 +FdatCov$Acc2 + FdatCov$Acc3)/3
    FdatCov$AccMDAvg <- (FdatCov$AccMD1 +FdatCov$AccMD2 + FdatCov$AccMD3)/3
    
    p[[3]] <- FdatCov %>%
      ggplot() +
      geom_line(aes(x = seq, 
                    y = AccAvg,
                    color = as.factor(BigN),
                    group = as.factor(j)), 
                size  = 0.1,
                show.legend = FALSE) +
      #scale_x_continuous(guide = guide_axis(angle = 45), limits = c(0.75, NA)) + 
      #scale_y_continuous(limits = c(0.3, 1), expand = c(0,0))+ 
      ylab("Avg Accuracy for Cov") + xlab("Iteration") + 
      facet_wrap(~DirType) +
      theme_minimal()
    
    p[[4]] <-  FdatCov %>%
      ggplot() +
      geom_line(aes(x = seq, 
                    y = AccMDAvg,
                    group = as.factor(j),
                    color = as.factor(BigN)), 
                size  = 0.1,
                show.legend = FALSE) +
      ylab("Avg Accuracy for out Cov Missing Data") + xlab("Iteration") + facet_wrap(~DirType)+
      theme_minimal()
  }
  pt <- ggpubr::ggarrange(plotlist = p, ncol = 2, nrow = 2)
  
  ptTot <- ggpubr::annotate_figure(pt,
                                   top = ggpubr::text_grob(paste0("Overlap: ", S[i,]$pClustOL,
                                                                  " Cov Corr: ", S[i,]$pC,
                                                                  " Pct Missing: ",S[i,]$missing,
                                                                  " Clust size: ",S[i,]$pClust),
                                                           color = "darkblue", 
                                                           face = "bold", 
                                                           size = 14))
  print(ptTot)
  
  rt <- ggpubr::ggarrange(plotlist = r, ncol = 2, nrow = 2)
  rtTot <- ggpubr::annotate_figure(rt,
                                   top = ggpubr::text_grob("Log Likelihood split",
                                                           color = "darkblue", 
                                                           face = "bold", 
                                                           size = 14))
  print(rtTot)
  ## Setting up the prelims plots
  pn <- list()
  pn[[1]] <- FdatnoCov %>%
    ggplot() +
    geom_line(aes(y = seq, 
                  x = round(LLFull,1), 
                  color = as.factor(BigN),
                  group = as.factor(j)),
              show.legend = FALSE) +
    #geom_vline(aes(xintercept = GTll[j,1])) +
    xlab("total Loglikelihood") + ylab("Iteration")+
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~DirType)+
    theme_minimal()
  
  
  pn[[2]] <- FdatnoCov %>%
    ggplot() +
    geom_point(aes(y = seq, 
                   x = round(OI,3), 
                   color = as.factor(BigN), 
                   group = as.factor(j)), 
               size  = 0.1,
               show.legend = FALSE) + 
    xlab("Omega Idx")+ylab("Iteration")+
    scale_x_continuous(guide = guide_axis(angle = 45)) +
    facet_wrap(~DirType)+
    theme_minimal()
  
  ptn <- ggpubr::ggarrange(plotlist = pn, ncol = 2, nrow = 2)
  
  ptnTot <- ggpubr::annotate_figure(ptn, 
                                    top = ggpubr::text_grob(paste0("Overlap: ", S[i,]$pClustOL, 
                                                                   " Cov Corr: ", S[i,]$pC,
                                                                   " Pct Missing: ",S[i,]$missing,
                                                                   " Clust size: ",S[i,]$pClust),
                                                            color = "darkblue", 
                                                            face = "bold", 
                                                            size = 14))
  print(ptnTot)
  plotRDS <- append(plotRDS, list(list(ptTot, rtTot, ptnTot)))
  
  i<- i+1
}
dev.off()
saveRDS(plotRDS, "SummaryPlotsMAR.rds")
```

```{r}
## final value plots for MAR
colnames(FinCov) <- c("i","j","LLFull", "LLG","LLX","LLZ","OI","ARI",
                      paste0("Acc",1:S[i,]$k_out ), "seq",
                      paste0("AccMD",1:S[i,]$k_out ))
#Simulation w/o covariates
colnames(FinnoCov) <- c("i","j","LLFull", "LLG","LLX","LLZ","OI","ARI","seq")

colnames(NWDirT) <- colnames(NWDir)

## Joining the data frame with types for NW list
## NW with covariates
FinCov <- left_join(FinCov , NWDirT, by = c("j" = "j", "i" = "i"))

## NW without covariates
FinnoCov <- left_join(FinnoCov , NWDirT, by = c("j" = "j", "i" = "i"))
FdatnoCov <- left_join(FdatnoCov, NWDirT, by = c("j" = "j", "i" = "i"))
FinCov$AccAvg <- (FinCov$Acc1 + FinCov$Acc2 + FinCov$Acc3)/3
FinCov$AccMDAvg <- (FinCov$AccMD1 + FinCov$AccMD2 + FinCov$AccMD3)/3
FinCov$OL <- factor(FinCov$OL,levels = c("NoOL", "2OL", "3OL", "allOL"))
FinCov$pC <- factor(FinCov$pC, levels = c("High", "Med","Low"))

FinnoCov$OL <- factor(FinnoCov$OL,levels = c("NoOL", "2OL", "3OL", "allOL"))
FinnoCov$pC <- factor(FinnoCov$pC, levels = c("High", "Med","Low"))

## Omega Index
pdf("SummaryBoxplotsMAR.pdf")
print(FinCov[FinCov$pClust == "equal", ] %>%
        ggplot()+
        geom_boxplot(aes(y = OI, x = as.factor(Missing), 
                         color = as.factor(DirType)))+
        ggtitle("Equal Sized clusters w/ Covariates")+ xlab("Percentage missing")+
        ylab("Omega Index")+labs(color ="NW direction")+lims(y = c(0.4, 1.1))+
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol =3))

print(FinCov[FinCov$pClust == "unequal", ] %>%
        ggplot()+
        geom_boxplot(aes(y = OI, x = as.factor(Missing), 
                         color = as.factor(DirType)))+
        ggtitle("Unequal clusters w/ Covariates")+ xlab("Percentage missing")+
        ylab("Omega Index")+labs(color ="NW direction")+lims(y = c(0.4, 1.1))+
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol =3))

## Full accuracy
print(FinCov[FinCov$pClust == "equal", ] %>%
        ggplot() +
        geom_boxplot(aes(y = AccAvg, x = as.factor(Missing), 
                         color = as.factor(DirType))) +
        ggtitle("Equal Sized clusters Accuracy")+ xlab("Percentage missing") +
        ylab("Prediction Accuracy") + labs(color ="NW direction") +
        theme(legend.position ='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol = 3))

print(FinCov[FinCov$pClust == "unequal", ] %>%
        ggplot() +
        geom_boxplot(aes(y = AccAvg, x = as.factor(Missing), 
                         color = as.factor(DirType))) +
        ggtitle("Unequal clusters Accuracy")+ xlab("Percentage missing") +
        ylab("Prediction Accuracy") + labs(color ="NW direction") +
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol = 3))

## Missing data accuracy
print(FinCov[FinCov$pClust == "equal", ] %>%
        ggplot() +
        geom_boxplot(aes(y = AccMDAvg, x = as.factor(Missing), 
                         color = as.factor(DirType))) +
        ggtitle("Equal Sized clusters Accuracy Missing data only")+ xlab("Percentage missing") +
        ylab("Prediction Accuracy Missing Data") + labs(color ="NW direction") +
        theme(legend.position ='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol = 3))

print(FinCov[FinCov$pClust == "unequal", ] %>%
        ggplot() +
        geom_boxplot(aes(y = AccMDAvg, x = as.factor(Missing), 
                         color = as.factor(DirType))) +
        ggtitle("Unequal clusters Accuracy Missing data only")+ xlab("Percentage missing") +
        ylab("Prediction Accuracy Missing Data") + labs(color ="NW direction") +
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol = 3))

### No covariates
print(FinnoCov[FinCov$pClust == "equal", ] %>%
        ggplot()+
        geom_boxplot(aes(y = OI, x = as.factor(Missing), 
                         color = as.factor(DirType)))+
        ggtitle("Equal Sized clusters w/o covariates")+ xlab("Percentage missing")+
        ylab("Omega Index")+labs(color ="NW direction")+lims(y = c(0.4, 1.1))+
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol =3))

print(FinnoCov[FinCov$pClust == "unequal", ] %>%
        ggplot()+
        geom_boxplot(aes(y = OI, x = as.factor(Missing), 
                         color = as.factor(DirType)))+
        ggtitle("Unequal clusters w/o covariates")+ xlab("Percentage missing")+
        ylab("Omega Index")+labs(color ="NW direction")+ lims(y = c(0.4, 1.1))+
        theme(legend.position='bottom', 
              strip.text.x = element_text(margin = margin(0.05,0,0.05,0, "cm"))) +
        facet_wrap(~OL+pC, ncol =3))
dev.off()

```

```{r}

param <- "InitParamMiss_Coh_MCAR_LASSO_Cont_2.rds"#"InitParamMiss_Cohesive_MCAR_B15_LASSO.rds"
param_c <- "InitParamMiss_Coh_MCAR_LASSO_Cont_2_comp.rds"#"InitParamMiss_Cohesive_MCAR_B15_LASSO_comb.rds"
fileName <- list.files("CoDAOP/CohesiveMCARCont_2/")#"CoDAOP/CohesiveMCAR_B15_LASSO/")
#Ncombo <- c(1:144)#c(1,2, 4:46, 48:72, 74:144)
S <- as.data.frame(readRDS(param_c))

S$missing <- rep(c(0,5,10,25,45), each =9)

df_op <- data.frame(matrix(ncol = 13,nrow = 0,0))
#idx <- c()

getData <- function(df){
  lens <- unlist(lapply(df, function(x ) length(x$OmegaIndex)))
  OI <- unlist(lapply(df, function(x ) last(x$OmegaIndex)))
  ARI <- unlist(lapply(df, function(x ) last(x$ARI)))
  ## Reading accuracy
  if(dim(df[[1]]$Acc)[1] > 0){
    Acc1 <- unlist(lapply(df, function(x ) last(x$Acc[,1])))
    Acc2 <- unlist(lapply(df, function(x ) last(x$Acc[,2])))
    Acc3 <- unlist(lapply(df, function(x ) last(x$Acc[,3])))
  }else{
    Acc1 <- 0
    Acc2 <- 0
    Acc3 <- 0
  }
  
  ## Reading Mean Sq error
   if(dim(df[[1]]$MSE)[1] > 0){
    MSE1 <- round(unlist(lapply(df, function(x ) last(x$MSE[,1]))), 4)
    MSE2 <- round(unlist(lapply(df, function(x ) last(x$MSE[,2]))) , 4)
    MSE3 <- round(unlist(lapply(df, function(x ) last(x$MSE[,3]))) , 4)
  }else{
    MSE1 <- 0
    MSE2 <- 0
    MSE3 <- 0
  }
  
  ## Reading missing data specific accuracy and mean sq error
  # Reading accuracy
  if(dim(df[[1]]$AccMD)[1] > 0){
    AccMD1 <- unlist(lapply(df, function(x ) last(x$AccMD[,1])))
    AccMD2 <- unlist(lapply(df, function(x ) last(x$AccMD[,2])))
    AccMD3 <- unlist(lapply(df, function(x ) last(x$AccMD[,3])))
  }else{
    AccMD1 <- 0
    AccMD2 <- 0
    AccMD3 <- 0
  }
  
  ## Reading Mean Sq error
   if(dim(df[[1]]$MSEMD)[1] > 0){
    MSEMD1 <- round(unlist(lapply(df, function(x ) last(x$MSEMD[,1]))), 4)
    MSEMD2 <- round(unlist(lapply(df, function(x ) last(x$MSEMD[,2]))) , 4)
    MSEMD3 <- round(unlist(lapply(df, function(x ) last(x$MSEMD[,3]))) , 4)
  }else{
    MSEMD1 <- 0
    MSEMD2 <- 0
    MSEMD3 <- 0
  }
  
  iter <- rep(1:(length(df)/2),each=2)
  return(cbind(lens,OI,ARI,Acc1,Acc2,Acc3,MSE1,MSE2,MSE3,AccMD1,AccMD2,AccMD3,MSEMD1,MSEMD2,MSEMD3,iter))
}


for(i in fileName){
  idx <- str_extract_all(i, "\\d+")[[1]][2]
  df <- readRDS(paste0("CoDAOP/CohesiveMCARCont_2/",i))
  df_reg <- df[[1]]
  df_sto <- df[[3]]
  df_nocov <- df[[2]]
  
  op <- rbind( cbind(idx,Rgr = "Reg",dir = c("D","U"), getData(df_reg)),
               cbind(idx,Rgr = "Sto",dir = c("D","U"), getData(df_sto)),
               cbind(idx,Rgr = "NoCov",dir = c("D","U"), getData(df_nocov)))
  
  df_op <- rbind(df_op, op)
  
}

df_op$idx <- as.integer(df_op$idx)
S$idx <- 1:dim(S)[1]

df_op <- left_join(df_op, S, by = join_by(idx == idx))

df_op$pC <- unlist(df_op$pC)
df_op$pClust <- unlist(df_op$pClust)
df_op$pConn <- unlist(df_op$pConn)
df_op$dirPct <- unlist(df_op$dirPct)
df_op$pClustOL <- unlist(df_op$pClustOL)
df_op$OI <- as.numeric(df_op$OI)
df_op$ARI <- as.numeric(df_op$ARI)
df_op$Acc1 <- as.numeric(df_op$Acc1)
df_op$Acc2 <- as.numeric(df_op$Acc2)
df_op$Acc3 <- as.numeric(df_op$Acc3)
df_op$MSE1 <- as.numeric(df_op$MSE1)
df_op$MSE2 <- as.numeric(df_op$MSE2)
df_op$MSE3 <- as.numeric(df_op$MSE3)
df_op$AccMD1 <- as.numeric(df_op$AccMD1)
df_op$AccMD2 <- as.numeric(df_op$AccMD2)
df_op$AccMD3 <- as.numeric(df_op$AccMD3)
df_op$MSEMD1 <- as.numeric(df_op$MSEMD1)
df_op$MSEMD2 <- as.numeric(df_op$MSEMD2)
df_op$MSEMD3 <- as.numeric(df_op$MSEMD3)
df_op$lens <- as.numeric(df_op$lens)


df_op$Accavg <- (df_op$Acc1 + df_op$Acc2 + df_op$Acc3)/3
df_op$MSEavg <- (df_op$MSE1 + df_op$MSE2 + df_op$MSE3)/3
df_op$AccavgMD <- (df_op$AccMD1 + df_op$AccMD2 + df_op$AccMD3)/3
df_op$MSEavgMD <- (df_op$MSEMD1 + df_op$MSEMD2 + df_op$MSEMD3)/3
df_op$pC <- factor(df_op$pC)
levels(df_op$pC) <- c("High","Low","Med")
df_op$pC <- factor(df_op$pC, levels = c("High", "Med","Low"))

df_op$pClustOL <- factor(df_op$pClustOL, levels = c( "NoOL","2GrpOL","3GrpOL","allOL"))

```

## For Binary cov

```{r, fig.width=15, fig.height=9}
library(RColorBrewer)
c <- expand.grid(unique(S$alphaLin), unique(S$missing), unique(S$lambda), unique(S$pClust))

for( i in 1:dim(c)[1]){
  p <- list()
  title <- paste0(c[i, 4]," clust with ",c[i,2] ," missing data and lambda ", c[i,3], " alphaLin", c[i,1])
  d <-  df_op %>%
    filter(pClust == c[i,4], alphaLin == c[i,1], missing == c[i,2], lambda == c[i,3])
  if(dim(d)[1] > 0 ){
    p[[1]] <- d %>%
      ggplot()+
      geom_boxplot(aes(x = pC, y = OI, color = Rgr))+ 
      #ggtitle(title)+ 
      ylab("Omega Index") + xlab("Correlation level")+ scale_color_brewer(palette = "Dark2")+
      theme( legend.position='none', panel.background = element_blank())+#theme_minimal()+
      facet_grid( vars(dir),vars(pClustOL)) 
    
    p[[2]] <- d %>%
      ggplot()+
      geom_boxplot(aes(x = pC, y = ARI, color = Rgr))+ 
      #ggtitle(title)+ 
      ylab("ARI") + xlab("Correlation level")+ scale_color_brewer(palette = "Dark2")+
      theme( legend.position='none', panel.background = element_blank())+#theme_minimal()+
      facet_grid( vars(dir),vars(pClustOL))
    
    p[[3]] <- d %>%
      ggplot()+
      geom_boxplot(aes(x = pC, y = Accavg , color = Rgr))+ 
      #ggtitle(title)+ 
      ylab("Average accuracy") + xlab("Correlation level")+ scale_color_brewer(palette = "Dark2")+
      theme( legend.position='none', panel.background = element_blank())+#theme_minimal()+
      facet_grid( vars(dir),vars(pClustOL))
    
    p[[4]] <- d %>%
      ggplot()+
      geom_boxplot(aes(x = pClustOL, y = lens, color = Rgr))+ 
      #ggtitle(title)+ 
      xlab("overlap") + ylab("Number of iteration")+scale_color_brewer(palette = "Dark2")+
      theme( legend.position='bottom', panel.background = element_blank())+#theme_minimal()+
      facet_grid( vars(dir),vars(pC))
    
    pt <- ggpubr::ggarrange(plotlist = p, ncol = 2, nrow = 2)
    ptTot <- ggpubr::annotate_figure(pt,top = ggpubr::text_grob(title,color = "darkblue",
                                                                face = "bold",size = 14))
    print(ptTot)
  }
}

```

## For continuous cov
```{r, fig.width=12, fig.height=7}
library(RColorBrewer)
c <- expand.grid(unique(S$alpha), unique(S$alphaLin), unique(S$missing), unique(S$pClust))
colnames(c) <- c("alpha","alphaLin","missing","pClust")
gbg <- matrix(0, nrow=0, ncol = dim(c)[2])

df_op$lambda <- as.factor(df_op$lambda)
for( i in 1:dim(c)[1]){
  p <- list()
  title <- paste0(c$pClust[i]," clust with ",c$missing[i],"% missing data and alphaLin ", c$alphaLin[i], " alpha = ", c$alpha[i])
  d <-  df_op %>%
    filter(alpha == c$alpha[i] ,pClust == c$pClust[i], 
           alphaLin == c$alphaLin[i], missing == c$missing[i])
  if(dim(d)[1] > 0 ){
    gbg <- rbind(gbg, c[i,])
    p[[1]] <- d %>%
      ggplot()+
      geom_boxplot(aes( y = OI, x = lambda, color = Rgr))+ 
      #ggtitle(title)+ 
      ylab("Omega Index") + xlab("lambda")+ scale_color_brewer(palette = "Set1")+
      theme( legend.position='none', panel.background = element_blank())+#theme_minimal()+
      facet_grid( vars(dir),vars(pClustOL)) 
    
    p[[2]] <- d %>%
      ggplot()+
      geom_boxplot(aes( y = ARI, x = lambda, color = Rgr))+ 
      #ggtitle(title)+ 
      ylab("ARI") + xlab("lambda")+ scale_color_brewer(palette = "Set1")+
      theme( legend.position='none', panel.background = element_blank())+#theme_minimal()+
      facet_grid( vars(dir),vars(pClustOL))
    
    p[[3]] <- d %>%
      filter(!(Rgr == "NoCov")) %>%
      ggplot()+
      geom_boxplot(aes( y = MSEavg , x = lambda, color = Rgr))+ 
      #ggtitle(title)+ 
      ylab("Average MSE") + xlab("Regression type")+ scale_color_brewer(palette = "Set1")+
      theme( legend.position='none', panel.background = element_blank())+#theme_minimal()+
      facet_grid( vars(dir),vars(pClustOL))
    
    p[[4]] <- d %>%
      filter(!(Rgr == "NoCov")) %>%
      ggplot()+
      geom_boxplot(aes( y = MSEavgMD , x = lambda, color = Rgr))+ 
      #ggtitle(title)+ 
      ylab("Average MSE for missing data") + xlab("Regression type")+ scale_color_brewer(palette = "Set1")+
      theme( legend.position='none', panel.background = element_blank())+#theme_minimal()+
      facet_grid( vars(dir),vars(pClustOL))
    
    p[[5]] <- d %>%
      ggplot()+
      geom_boxplot(aes(x = pClustOL, y = lens, color = Rgr))+ 
      #ggtitle(title)+ 
      xlab("overlap") + ylab("Number of iteration")+scale_color_brewer(palette = "Set1")+
      theme( legend.position='bottom', panel.background = element_blank())+#theme_minimal()+
      facet_grid( vars(dir),vars(lambda))
    
    pt <- ggpubr::ggarrange(plotlist = p, ncol = 3, nrow = 2)
    ptTot <- ggpubr::annotate_figure(pt,top = ggpubr::text_grob(title,color = "darkblue",
                                                                face = "bold",size = 14))
    print(ptTot)
  }
}

```



```{r}
## Comparing the OI for stochastic regression vs regression
df_2 <- data.frame(matrix(ncol = 9,nrow = 0,0))

for(i in fileName){
  idx <- str_extract_all(i, "\\d+")[[1]][2]
  df <- readRDS(paste0("CoDAOP/CohesiveMCARCont_2/",i))
  df_reg <- df[[1]]
  df_sto <- df[[3]]
  df_nocov <- df[[2]]
  
  df_2 <- rbind(df_2, cbind(idx, unlist(lapply(df_reg, function(x ) last(x$OmegaIndex))),
                            unlist(lapply(df_sto, function(x ) last(x$OmegaIndex))),
                            unlist(lapply(df_nocov, function(x ) last(x$OmegaIndex))),
                            unlist(lapply(df_reg, function(x ) length(x$OmegaIndex))),
                            unlist(lapply(df_sto, function(x ) length(x$OmegaIndex))),
                            unlist(lapply(df_nocov, function(x ) length(x$OmegaIndex))),
                            rep(1:15, each =2), 
                            rep(c("D","U"), times = 15)
                            ))
  
}
colnames(df_2) <- c("idx","reg","sto","nocov","lenR","lenS","lenNC","iter","dir")
df_2$reg <- as.numeric(df_2$reg)
df_2$sto <- as.numeric(df_2$sto)
df_2$lenR <- as.numeric(df_2$lenR)
df_2$lenS <- as.numeric(df_2$lenS)
df_2$OIdiff <- df_2$sto - df_2$reg
df_2$lendiff <- df_2$lenS - df_2$lenR
df_2 %>% ggplot() +
  geom_point(aes(x = lendiff, y = OIdiff, color =dir))+
  facet_wrap(~dir)

## Looking specifically at iteration 10 of 107th idx. directed
i <- fileName[10]
df <- readRDS(paste0("CoDAOP/CohesiveMCARCont/",i))

```




```{r}
## Creating the difference table for iteration between regression adn stochastic regression

df_lens <- df_op %>%
  select(idx, Rgr, dir, lens, iter) %>%
  mutate(grp = paste0(Rgr, "_",dir))%>%
  select(-c(Rgr, dir)) %>%
  pivot_wider(names_from = grp, values_from = c(lens)) %>%
  mutate(diff_SR = Sto_D - Reg_D )

## Plot the difference between sto and reg

df_lens %>% ggplot()+
  geom_histogram(aes(x = diff_SR))+ scale_x_continuous(trans = "log10")


df_OI <- df_op %>%
  select(idx, Rgr, dir, OI, iter) %>%
  mutate(grp = paste0(Rgr, "_",dir))%>%
  select(-c(Rgr, dir)) %>%
  pivot_wider(names_from = grp, values_from = c(OI)) %>%
  mutate(diff_OI = Sto_D - Reg_D )

## Plot the difference between sto and reg

df_OI %>% ggplot()+
  geom_histogram(aes(x = diff_OI))+ scale_x_continuous(trans = log10)

```



```{r}
x <- 1:10
p <- 1-exp(-1* x) 

plot(x, p)  
```










