---
title: "LargeNWProcessing"
output: pdf_document
date: "2026-01-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("C:/Users/gauph/Documents/StatisticsMS_PhD/Wastewater-Surveillance-OSU/Sunbelt23/Code/CoDACov.R")

```

## Reading large NW output

```{r}
N_600 <- rep(600,6) #2000, 10000
N_2000 <- rep(2000,6)
nc_600 <- c(4,6,8,10,13,15)
nc_2000 <- c(10, 15, 25, 35 ,45, 55)
# for N = 10000 c(25,35,45,55,65,75)
# for N =2000 c(10, 15, 25, 35 ,45, 55)
# for N = 600c(4,6,8,10,13,15)
alpha_600 <- c(0.0001,0.0003,0.0005,0.0007,0.001,0.003,0.005,0.007,0.01)
alpha_2000 <- c(1e-05, 3e-05, 5e-05,7e-05,1e-04,3e-04,5e-04,7e-04,0.001,0.003,0.005,0.007,0.01)
dirV <- c("D","U")
o <- 6
k <- 6
## reading the output data
folderId <- paste0(getwd(),"/LargeSimulatedDataOutput/")
files <- list.files(folderId)
```


```{r}
## Save N,nc, alpha, direction, OI, MSE, ACC, 
op <- matrix(0, ncol = 17, nrow =0)
## Reading the output data 
fid <- 1
for(f in files[1:6]){
  id <- 1
  df <- readRDS(paste0(folderId, f))
  print(length(df))
  nc <- nc_600[fid]
  N <- N_600[fid]
  fid <- fid+1
    for(dir in dirV){
    for(alpha in alpha_600){
      if(id <= length(df)){
        if(length(df[[id]]) > 0){
          op <- rbind(op, c(N,nc,alpha,dir,df[[id]]$OmegaIndex, df[[id]]$MSE, df[[id]]$Acc ))
        }else{
          op <- rbind(op, c(N,nc,alpha,dir,0, rep(0, o), rep(0, k) ))
        }
      }else{
          op <- rbind(op, c(N,nc,alpha,dir,0, rep(0, o), rep(0, k) ))
        }
      id <- id+1
    }
  }
  
}

fid <- 1
for(f in files[7:12]){
  id <- 1
  df <- readRDS(paste0(folderId, f))
  nc <- nc_2000[fid]
  N <- N_2000[fid]
  fid <- fid+1
    for(dir in dirV){
    for(alpha in alpha_2000){
      if(id < length(df)){
        if(length(df[[id]]) > 0){
          op <- rbind(op, c(N,nc,alpha,dir,df[[id]]$OmegaIndex, df[[id]]$MSE, df[[id]]$Acc ))
        }else{
          op <- rbind(op, c(N,nc,alpha,dir,0, rep(0, o), rep(0, k) ))
        }
      }
      id <- id+1
    }
  }
}
op <- as.data.frame(op)
colnames(op) <- c("N","nc","alpha","direction","OI",paste0(1:o,"MSE"),paste0(1:k,"Acc")) 

op[,c(1:3,5:17)] <- as.data.frame(apply(op[,c(1:3,5:17)],2,as.numeric))

```

## What is the maximum 
```{r}

MAX_OI <- op %>% group_by(N, nc, direction) %>% filter(OI == max(OI))#summarise(Max_OI = max(OI))

MAX_OI$MSEavg <- rowSums(MAX_OI[,6:11])/6
MAX_OI$Accavg <- rowSums(MAX_OI[,12:17])/6
MAX_OI <- MAX_OI[,-c(6:17)]

```


