---
title: "Multiple Start Analysis"
output: pdf_document
date: "2026-02-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reading data

```{r}
## read the hyperparam combinations
filePath <- "C:/Users/gauph/Documents/StatisticsMS_PhD/Wastewater-Surveillance-OSU/Sunbelt23/Code/FinalTestingParamComboFiles/4clustersims_comb_MultipleStarts.rds"
S <- readRDS(filePath)

SaveFolder <- "C:/Users/gauph/Documents/StatisticsMS_PhD/Wastewater-Surveillance-OSU/Sunbelt23/Code/FinalTestingParamComboFiles/ResultsFolder/SubsetResults/"
#covariate data
covOP <- readRDS(paste0(SaveFolder, "MultInitializationScale_covOP.rds"))
metrics_cov <- readRDS(paste0(SaveFolder, "MultInitializationScale_metricsCov.rds"))

#no covariate data
nocovOP <- readRDS(paste0(SaveFolder, "MultInitializationScale_nocovOP.rds"))
metrics_nocov <-  readRDS(paste0(SaveFolder, "MultInitializationScale_metricsnoCov.rds"))
metrics_nocov$dir <- nocovOP$Dir
colors <-  c("brown4","blue4","sienna3","orangered","chartreuse4", "darkorchid","cornflowerblue", "coral2","chocolate3", 
             "gold1","cyan2","slateblue3","salmon4",
             "darkolivegreen1", "aquamarine","firebrick2", "maroon2","dodgerblue" )
```

```{r}
## Front for covariate method
cols_to_select_cov <- c("WeightedBinaryDispersionScoreW","WeightedDispersionScoreW")
metric_na <- which(apply(metrics_cov, 1, function(x) any(is.na(x))))

if(length(metric_na) > 0){
  metrics_cov <- metrics_cov[-c(metric_na),]
  #covOP <- covOP[-c(metric_na),]  
}

length(which(metrics_cov$Failure == FALSE))
metrics_cov <- metrics_cov %>% select(-Failure)
metrics_cov$degree01 <- metrics_cov$degree0+metrics_cov$degree1
metrics_cov <- HyperParameterSelection(metrics_cov, cols_to_select_cov, TRUE)

## Front for no covariate method
cols_to_select <- c("SdMeanConductanceW")
metrics_nocov <- HyperParameterSelection(metrics_nocov, cols_to_select, FALSE)

## Set factor levels for overlap
metrics_cov$OL <- factor(metrics_cov$OL, levels = c("NoOL","5Pct","10Pct","15Pct","20Pct","25Pct"))
metrics_nocov$OL <- factor(metrics_nocov$OL, levels = c("NoOL","5Pct","10Pct","15Pct","20Pct","25Pct"))

## set factor levels for missing data 
metrics_cov$PctMiss <- factor(metrics_cov$PctMiss, levels = c("0","5","10","15","20"))
metrics_nocov$PctMiss <- 0

## set factor level for alpha lambdas 
metrics_cov$alpha <- factor(metrics_cov$alpha, levels = c("1e-05", "5e-05", "1e-04", "5e-04", "0.001"))
metrics_nocov$alpha <- factor(metrics_nocov$alpha, levels = c("1e-05", "5e-05", "1e-04", "5e-04", "0.001"))

metrics_cov$lambda_bin <- factor(metrics_cov$lambda_bin, levels = c("1e-05", "1e-04"))
metrics_cov$lambda_lin <- factor(metrics_cov$lambda_lin, levels = c("1e-05", "1e-04"))

## removing group size variable for plotting
metrics_cov <- metrics_cov %>% select(-c(groupSize))
metrics_nocov <- metrics_nocov %>% select(-c(groupSize))

## unlist dir
metrics_cov$dir <- unlist(metrics_cov$dir)
metrics_nocov$dir <- unlist(metrics_nocov$dir)

```


```{r}

df <- metrics_cov %>% filter(front == 1)

df <- df %>% select(-c(front))

## performing non dominated sorting again
cols_to_select_cov <- c("WeightedBinaryDispersionScoreW","WeightedDispersionScoreW")
df <- HyperParameterSelection(df, cols_to_select_cov, TRUE)

df <- df %>% filter(front ==1)

```

## Pairwise comparison rate

```{r}
pairwise <- df %>% filter(unassigned <= degree01 ) %>%
  group_by(OL, dir,bigN, PctMiss ) %>% 
  filter(front == 1) %>%
  summarise(mean_OI = mean(OI),
            median_OI = median(OI),
            sd = sd(OI),
            max_OI = max(OI),
            min_OI = min(OI)) %>%
  ungroup()
p  <- pairwise %>%
  ggplot()+
  geom_point(aes(x = interaction(dir,OL), y = mean_OI, color = dir ))+
  geom_line(aes(x = interaction(dir,OL), y = mean_OI, group = interaction(bigN,OL)), alpha=0.5)+
  facet_wrap(~PctMiss)+ ylim(0,1)+
  theme(legend.position = "bottom", 
        panel.background = element_blank(), 
        axis.text.x = element_text(angle = 90, vjust = 0.75))
p

dircomp <- pairwise %>% 
  select(OL, dir, PctMiss,bigN, median_OI) %>%
  pivot_wider(values_from = median_OI, names_from = dir) %>%
  dplyr::mutate(pctImp = ((directed - undirected)/undirected)*100)

AvgPctImp <- dircomp %>% 
  group_by(OL, PctMiss) %>% 
  summarise(avgPctImp = median(pctImp, na.rm = T),
            meanchange = median(directed, na.rm = T) - median(undirected, na.rm = T),
            pctImp_postavg = (median(directed, na.rm = T) - median(undirected, na.rm = T))/median(undirected, na.rm = T)*100 )

p <- AvgPctImp %>% 
  ggplot()+ 
  geom_point(aes(x = OL, y = avgPctImp, color = PctMiss))+
  geom_line(aes(x = OL, y = avgPctImp, group = PctMiss),linetype = "dashed", alpha = 0.6)+
  ylab("Median Percent Improvement") + 
  xlab("Percent cluster overlap")+
  labs(color = "Percent missing")+
  geom_hline(aes( yintercept  =0), alpha = 0.7)+
  scale_color_manual(values = colors)+
  theme(legend.position = "bottom", 
        panel.background = element_blank())
p

AvgPctImp %>% 
  ggplot()+ 
  geom_point(aes(x = OL, y = meanchange, color = PctMiss))+
  geom_line(aes(x = OL, y = meanchange, group = PctMiss),linetype = "dashed", alpha = 0.6)+
  geom_hline(aes( yintercept  =0), alpha = 0.7)+
  scale_color_manual(values = colors)+
  theme(legend.position = "bottom", 
        panel.background = element_blank())

AvgPctImp %>% 
  ggplot()+ 
  geom_point(aes(x = OL, y = pctImp_postavg, color = PctMiss))+
  geom_line(aes(x = OL, y = pctImp_postavg, group = PctMiss),linetype = "dashed", alpha = 0.6)+
  geom_hline(aes( yintercept  =0), alpha = 0.7)+
  scale_color_manual(values = colors)+
  theme(legend.position = "bottom", 
        panel.background = element_blank())
```

```{r}
metrics_nocov$PctMiss <- 0
##Combined cov and no cov datatset
OIcomb <- rbind(df %>% filter(front ==1) %>%
                  dplyr::mutate(covType = "Covariate") %>% 
                  select(bigN,OL,PctMiss,dir,covType,OI,front),
                metrics_nocov %>% #filter(front ==1) %>%
                  dplyr::mutate(covType = "No Covariate") %>% 
                  select(bigN,OL,PctMiss,dir,covType,OI,front)) %>%
  filter(front == 1)

OIcomb   %>% ggplot()+
  geom_boxplot(aes(x = OL, y = OI, color = covType)) +
  facet_wrap(PctMiss~dir, ncol = 2)+ 
  theme(legend.position = "bottom", panel.background = element_blank())

OI_range <- OIcomb %>% 
  group_by(OL,PctMiss,dir,covType) %>% 
  summarise(median_OI = median(OI),
            mean_OI = mean(OI),
            sd_OI = sd(OI),
            min_OI = min(OI),
            max_OI = max(OI))

OI_range %>% ggplot() +
  geom_point(aes(x = OL, y = mean_OI, color =interaction(covType, PctMiss )))+
  geom_line(aes(x = OL, y = mean_OI, color =interaction(covType, PctMiss ), group = interaction(covType, PctMiss ) ))+
  geom_point(aes(x = OL, y = mean_OI+sd_OI, color = interaction(covType, PctMiss )))+
  geom_line(aes(x = OL, y = mean_OI+sd_OI,color =interaction(covType, PctMiss ), 
                group = interaction(covType, PctMiss )),linetype = "dashed", alpha = 0.6)+  
  geom_point(aes(x = OL, y = mean_OI-sd_OI, color = interaction(covType, PctMiss )))+
  geom_line(aes(x = OL, y = mean_OI-sd_OI, color =interaction(covType, PctMiss ), 
                group = interaction(covType, PctMiss )),linetype = "dashed", alpha = 0.6)+
  scale_color_manual(values = colors)+ylab("Omega Index")+xlab("Overlap Level")+ labs(color = "") + 
  facet_wrap(~dir)+# ggtitle(pct)+ylim(-0.3,1.1)+
  theme(legend.position = "bottom", panel.background = element_blank())

# 
p <-  OI_range %>% ggplot(aes(x = OL, y = mean_OI,ymin = mean_OI-sd_OI, ymax = mean_OI+sd_OI ))+
  geom_errorbar(aes(color =interaction(covType, PctMiss) ), alpha =0.7, width = 0.15)+
  geom_point(aes(color =interaction(covType, PctMiss) ))+
  geom_line(aes(x = OL, y = mean_OI, color =interaction(covType, PctMiss ), group = interaction(covType, PctMiss ) ))+
  ylab("Mean Omega Index") + xlab("Percent cluster overlap")+labs(color = "W/Wo covariates")+
  scale_color_manual(values = colors)+
  facet_wrap(~dir)+ #ylim(-0.3,1.1)+
  theme(legend.position = "bottom", panel.background = element_blank())
p

p <-  OI_range %>% ggplot(aes(x = OL, y = mean_OI,ymin = min_OI, ymax = max_OI ))+
  geom_errorbar(aes(color =interaction(covType, PctMiss) ), alpha =0.7, width = 0.15)+
  geom_point(aes(color =interaction(covType, PctMiss) ))+
  geom_line(aes(x = OL, y = mean_OI, color =interaction(covType, PctMiss ), group = interaction(covType, PctMiss ) ))+
  ylab("Mean Omega Index") + xlab("Percent cluster overlap")+labs(color = "W/Wo covariates")+
  scale_color_manual(values = colors)+
  facet_wrap(~dir)+ #ylim(-0.3,1.1)+
  theme(legend.position = "bottom", panel.background = element_blank())
p

```

```{r}
gbg <- df %>% filter(front == 1) %>% 
  select(dir, effective_nc, PctMiss, OL) %>% 
  group_by( dir,effective_nc,  PctMiss,OL) %>%
  dplyr::summarise(n = n(), .groups = "drop") %>%
  group_by(dir,PctMiss,OL) %>%
  dplyr::mutate(percent = n / sum(n) * 100) %>%
  ungroup()

gbgMedPct <- df %>% filter(front == 1) %>% 
  select(bigN,dir, effective_nc, PctMiss, OL) %>% 
  group_by(bigN, dir,effective_nc,  PctMiss,OL) %>%
  dplyr::summarise(n = n(), .groups = "drop") %>%
  group_by(bigN,dir,PctMiss,OL) %>%
  dplyr::mutate(percent = n / sum(n) * 100) %>%
  ungroup() %>% group_by(dir, effective_nc,PctMiss,OL) %>%
  dplyr::summarise(medianPct = median(percent))

p <- gbg %>% filter(effective_nc == 4) %>% ggplot()+
  geom_point(aes( x = PctMiss, y = percent, color = OL))+
  geom_line(aes( x = PctMiss, y = percent, color = OL, group = OL))+
  ylab("Percent of correctly selected cluster size") + 
  labs(color="Percent cluster overlap")+
  xlab( "Percent missing covariates")+
  scale_color_manual(values = colors)+
  facet_wrap(~dir)+ ylim(0,100)+
  theme(legend.position = "bottom", panel.background = element_blank())
p

p <- gbg %>% filter(effective_nc == 4) %>% ggplot()+
  geom_point(aes( x = OL, y = percent, color = PctMiss))+
  geom_line(aes( x = OL, y = percent, color = PctMiss, group = PctMiss))+
  ylab("Percent of correctly selected cluster size") + 
  xlab("Percent cluster overlap")+
  labs(color = "Percent missing covariates")+
  scale_color_manual(values = colors)+
  facet_wrap(~dir)+ ylim(0,100)+
  theme(legend.position = "bottom", panel.background = element_blank())
p

p <- gbgMedPct %>% filter(effective_nc == 4) %>% ggplot()+
  geom_point(aes( x = OL, y = medianPct, color = PctMiss))+
  geom_line(aes( x = OL, y = medianPct, color = PctMiss, group = PctMiss))+
  ylab("Percent of correctly selected cluster size") + 
  xlab("Percent cluster overlap")+
  labs(color = "Percent missing covariates")+
  scale_color_manual(values = colors)+
  facet_wrap(~dir)+ ylim(0,100)+
  theme(legend.position = "bottom", panel.background = element_blank())
p

```

## find the variance and correlation of the multiple starts
```{r}

nsim_summary <- metrics_cov %>% group_by(bigN, OL, PctMiss, dir, alpha, lambda_bin, lambda_lin, nc2) %>%
  summarise(OI_variance = var(OI),
            OI_sd = sd(OI),
            OI_mean = mean(OI),
            OI_median = median(OI),
            OI_min =  min(OI),
            OI_max = max(OI),
            cor_ll =  cor(LL, OI),
            cor_iters = cor(NumIters, OI),
            count = n()) %>% ungroup()


#nsim_na <- which(apply(nsim_summary, 1, function(x) any(is.na(x))))

#if(length(nsim_na) > 0){
#  nsim_summary <- nsim_summary[-c(nsim_na),]
  #covOP <- covOP[-c(metric_na),]  
#}
nsim_summary %>% ggplot()+
  geom_boxplot(aes(color = factor(nc2), y = cor_ll, x = factor(alpha) ))+
  facet_grid(rows = vars(OL), cols = vars(PctMiss))+
    theme(legend.position = "bottom", panel.background = element_blank())

nsim_summary %>% filter(nc2 ==4) %>% ggplot()+
  geom_boxplot(aes(color = factor(PctMiss), y = cor_ll, x = factor(alpha) ))+
  facet_wrap(~OL)+
    theme(legend.position = "bottom", panel.background = element_blank())

nsim_summary %>% ggplot()+
  geom_boxplot(aes(color = factor(nc2), y = OI_sd, x = factor(alpha) ))+
  facet_grid(rows = vars(OL), cols = vars(PctMiss))+
    theme(legend.position = "bottom", panel.background = element_blank())

metrics_cov %>% filter(OL == "NoOL", dir == "directed", bigN ==1)  %>% ggplot() +
  geom_point(aes(x =LL, y = OI , color = factor(nc2)))+ facet_grid(vars(PctMiss), vars(alpha))

metrics_cov %>% filter(OL == "NoOL", dir == "directed", bigN ==1)  %>% ggplot() +
  geom_point(aes(x =NumIters , y = OI , color = factor(nc2)))+ facet_grid(vars(PctMiss), vars(alpha))

metrics_cov %>% filter(OL == "NoOL", dir == "directed", bigN ==2)  %>% ggplot() +
  geom_point(aes(x =NumIters , y = OI , color = factor(nc2)))+ facet_grid(vars(PctMiss), vars(alpha))
metrics_cov %>% filter(OL == "NoOL", dir == "directed", bigN ==3)  %>% ggplot() +
  geom_point(aes(x =NumIters , y = OI , color = factor(nc2)))+ facet_grid(vars(PctMiss), vars(alpha))

```
